### ISSUE TITLE
your software is broken

### ISSUE THREAD

**Issue by tunage** [marcj/php-rest-service#22]
I copy/paste your sample code and all I get is

Fatal error: Class 'MyRestApi\Admin' not found in /usr/home/www/tmp/index.php on line 5

It would of been nice to use, but it's broke.

**Comment by reimax** [comment]
+1, sample code not work

**Comment by ntvsx193** [comment]
Really?
Are you create file {{/MyRestApi/Admin.php}}?

**Comment by marcj** [comment]
probably because you haven't setup autoloading correctly.

**Comment by Fever905** [comment]
Same problem here and I do have autoloading setup correct.  Is the path relative?
