### ISSUE TITLE
 summary of all routes problem

### ISSUE THREAD

**Issue by espekkaya** [marcj/php-rest-service#32]
Hi,
You said that as "Can return a summary of all routes or one route through OPTIONS method based on PHPDoc (if OPTIONS is not overridden)"

But I have called class like that;
\RestService\Server::create('/recipe', '\CorsApi\Recipe')
    ->collectRoutes()
    ->run();

and my url is "http://localhost:8080/sample/restApi/recipe/" but server returns json content is ;
{
    "status": 400,
    "error": "RouteNotFoundException",
    "message": "There is no route for ''."
}

How can I show all available methods? I haven't figured it out.

Thank you.

**Comment by marcj** [comment]
you nee to use `HTTP OPTIONS`, not `HTTP GET`

**Comment by espekkaya** [comment]
Thank you Marcus.Problem is solved.
