### ISSUE TITLE
get an error  ' count(): Parameter must be an array or an object that implements'

### ISSUE THREAD

**Issue by espekkaya** [marcj/php-rest-service#42]
Hello,

I'm using php 7. When I called my class method , I have hot an error below;

```
<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>C:\xampp\htdocs\piksel-ng\api\vendor\marcj\php-rest-service\RestService\Server.php</b> on line <b>836</b><br />
```

**Comment by typix** [comment]
disable PHP warnings, or insert:
`else $regexArguments = [];`
around line 813 in Server.php

**Comment by supersonictw** [comment]
The bug has been resolved in `dev-master`.
But it seem haven't been pushed to [packagist](https://packagist.org/packages/marcj/php-rest-service).

To resolve it, just need to switch "*" to "dev-master" until the author update.
